### ISSUE TITLE
December 2019 - Iteration Plan

### ISSUE THREAD

**Issue by iketheadore** [SkycoinProject/skycoin#182]
This plan captures our work in **December**.  This is a 4 weeks work plan. 

### Legend of annotations

|  Mark |      Description      |
|-------|------------------|
| 🏃      | Work in progress |

## Core
- [x] Prepare to upgrade to Go 1.13 and migrate to use go modules #176. **Ignored**, see details in the issue and #178
- [ ] Config to control maximum incoming connections #126 
- [ ] Early shutdown causes panic #123
- [x] 🏃 Add linux AppImage install instruction doc #120 @iketheadore 
- [ ] 🏃 Optimize wallet address scanning by searching from last to first #20 @iketheadore 
- [x] 🏃 Add an API endpoint to scan wallet addresses #200 @iketheadore 
- [x] Support wallet address scanning in the CLI tool #21 
- [ ] Temporary wallet load feature #116 
- [ ] Mechanism to communicate specific errors to the electron client #62
- [ ] Measure db bucket length can take a long time / stall #54
- [ ] Review handling of Close() errors for critical files #88
- [ ] Investigate build parallelization in travis #82
- [ ] Remove "private" peers from Pex and daemon #79
- [ ] Update Electron to latest stable version #184

## API
- [x]  Add calculated_hours to /uxout and /address_uxouts #84 @iketheadore 
- [x]  Include SrcTransaction in verbose transaction inputs #59 @iketheadore 
- [ ] Support "collection" wallets in REST API #22
- [ ] API endpoint to expose configuration parameters for use by web/mobile wallet multicoin API #92
- [x] Add begin and end pagination parameters to /transactions #121 
- [ ] Logging error responses from v2 APIs should exclude "data" #57 
- [x] 🏃 Bug in `/api/v1/wallet/create` - addresses scan does not function as expected #201

## UI
- [x] 🏃 Upgrade to Angular 8 #186  @Senyoret1 
- [x] Offline Wallet Transaction Signing Feature wallet #124
- [x] 🏃 Do not close modal windows by clicking on the background #11 @Senyoret1 
- [x] 🏃 Change the colors of DoubleButtonComponent #32 @Senyoret1 
- [x] 🏃 Do not show all transactions in the history immediately #24 @Senyoret1 
- [x] 🏃 Better error msg for when unable to connect with the hw wallet daemon #16  @Senyoret1 
- [x] 🏃 Fix the send all button of the advanced form #189 @Senyoret1 
- [x] 🏃 Display only one menu on the desktop wallet #192 @Senyoret1 

## CI/CD
- [x] Exit the travis build when got lint error #179

**Comment by Senyoret1** [comment]
@iketheadore All UI changes and the update for the Electron version were added to https://github.com/SkycoinProject/skycoin/pull/186 .
