### ISSUE TITLE
February 2020 - Iteration Plan

### ISSUE THREAD

**Issue by iketheadore** [SkycoinProject/skycoin#215]
This plan captures our work in **February**.  This is a 4 weeks work plan. 

### Legend of annotations

|  Mark |      Description      |
|-------|------------------|
| 🏃      | Work in progress |

## Core
- [x] 🏃 Config to control maximum incoming connections #126 
- [ ] Early shutdown causes panic #123
- [ ] 🏃 Optimize wallet address scanning by searching from last to first #20 @iketheadore 
- [ ] 🏃 Temporary wallet load feature #116 
- [ ] Mechanism to communicate specific errors to the electron client #62
- [ ] Measure db bucket length can take a long time / stall #54
- [ ] Review handling of Close() errors for critical files #88

- [x] Remove "private" peers from Pex and daemon #79
- [x] Update Electron to latest stable version #184

## API
- [ ] Support "collection" wallets in REST API #22
- [ ] API endpoint to expose configuration parameters for use by web/mobile wallet multicoin API #92
- [x] 🏃 Logging error responses from v2 APIs should exclude "data" #57 

## UI
- [ ] Wallet added during syncing does not scan ahead enough addresses #68 

## CI/CD
- [x] Investigate build parallelization in travis #82
