### ISSUE TITLE
March 2020 - Iteration Plan

### ISSUE THREAD

**Issue by iketheadore** [SkycoinProject/skycoin#237]
This plan captures our work in **March**.  This is a 4 weeks work plan. 

### Legend of annotations

|  Mark |      Description      |
|-------|------------------|
| 🏃      | Work in progress |

## Core
- [ ] Early shutdown causes panic #123
- [ ] 🏃 Refactor bip44 wallet file struct to support multiple accounts #249
- [ ] 🏃 Optimize wallet address scanning by searching from last to first #20 @iketheadore 
- [ ] 🏃 Temporary wallet load feature #116 
- [ ] Mechanism to communicate specific errors to the electron client #62
- [x] Measure db bucket length can take a long time / stall #54
- [x] Review handling of Close() errors for critical files #88
- [x] Wallet build hanging at code signing step for osx #231
- [x] Do not upgrade DB version unless the the DB buckets are changed #229
- [x] Build fail frequently for TestDBVerifyLogic #228
- [x] Check that wallet can be created when offline #42
- [x] Move some operations out of the daemon run loop #48 

## API
- [ ] Support "collection" wallets in REST API #22
- [ ] API endpoint to expose configuration parameters for use by web/mobile wallet multicoin API #92
- [ ] API endpoint for total number of transactions #23
- [ ] Include the BIP21 prefix in the /health endpoint #12
- [ ] 🏃Unnecessary change addresses are being created for bip44 wallets #246
- [ ] Possible resource exhaustion in CreateTransaction from wallet #61

## UI
- [ ] Wallet added during syncing does not scan ahead enough addresses #68 
- [ ] Add "xpub" frontend wallet support #14
- [ ] Bip44 Wallet Frontend Support #18
- [ ] Unconfirmed txns in history view are not marked as unconfirmed #43
